name: Simple Workflow with Branch-Dependent Variables

on: [push]

env:
  MY_GLOBAL_VARIABLE: >-
    ${{ 
      (github.ref == 'refs/heads/main') && 'e4u-stabil4u-gasag-prod' ||
      startsWith(github.ref, 'refs/heads/feature/') && 'e4u-stabil4u-dev' ||
      (github.ref == 'refs/heads/dev') && 'e4u-stabil4u-dev' 
    }}
  ANOTHER_GLOBAL_VAR: >-
    ${{ 
      (github.ref == 'refs/heads/main') && 'e4u-stabil4u-gasag-prod' ||
      startsWith(github.ref, 'refs/heads/feature/') && 'e4u-stabil4u-dev' ||
      (github.ref == 'refs/heads/dev') && 'e4u-stabil4u-dev' 
    }}

jobs:
  print_message:
    runs-on: ubuntu-latest

    steps:
    - name: Print using global variables
      run: |
        echo $MY_GLOBAL_VARIABLE
        echo $ANOTHER_GLOBAL_VAR
