name: Simple Workflow with Branch-Dependent Variables

on: [push]

env:
  MY_GLOBAL_VARIABLE: >-
    ${{ 
      (github.ref == 'refs/heads/main') && 'Main Branch' ||
      (github.ref == 'refs/heads/dev') && 'Development Branch' ||
      'Other Branch'
    }}
  ANOTHER_GLOBAL_VAR: >-
    ${{ 
      (github.ref == 'refs/heads/main') && 'Main Variable' ||
      (github.ref == 'refs/heads/dev') && 'Dev Variable' ||
      'Other Variable'
    }}

jobs:
  print_message:
    runs-on: ubuntu-latest

    steps:
    - name: Print using global variables
      run: |
        echo $MY_GLOBAL_VARIABLE
        echo $ANOTHER_GLOBAL_VAR
